name: Make Docker Image

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          tags: dustinupdyke/ghosts-shadows:latest
          push: true
          context: src/.
          file: ./src/Dockerfile
